<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKlokvff\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKlokvff/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKlokvff.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKlokvff\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKlokvff\appDevDebugProjectContainer([
    'container.build_hash' => 'Klokvff',
    'container.build_id' => 'e98fa3e1',
    'container.build_time' => 1551974613,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKlokvff');
