<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWjqj0mk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWjqj0mk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWjqj0mk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWjqj0mk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWjqj0mk\appDevDebugProjectContainer([
    'container.build_hash' => 'Wjqj0mk',
    'container.build_id' => 'fd925c4a',
    'container.build_time' => 1552069315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWjqj0mk');
