<?php

namespace ConnexionBundle\Repository;

/**
 * FluxRSSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxRSSRepository extends \Doctrine\ORM\EntityRepository
{
}
