<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPj4fkx1\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPj4fkx1/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPj4fkx1.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPj4fkx1\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPj4fkx1\appDevDebugProjectContainer([
    'container.build_hash' => 'Pj4fkx1',
    'container.build_id' => 'b15dd503',
    'container.build_time' => 1552318129,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPj4fkx1');
