<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMh4c20z\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMh4c20z/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMh4c20z.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMh4c20z\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMh4c20z\appDevDebugProjectContainer([
    'container.build_hash' => 'Mh4c20z',
    'container.build_id' => '58d16b38',
    'container.build_time' => 1552055577,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMh4c20z');
