<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMa7h9me\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMa7h9me/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMa7h9me.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMa7h9me\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMa7h9me\appProdProjectContainer([
    'container.build_hash' => 'Ma7h9me',
    'container.build_id' => '7ed92657',
    'container.build_time' => 1551810638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMa7h9me');
