<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMowfjkn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMowfjkn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMowfjkn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMowfjkn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMowfjkn\appProdProjectContainer([
    'container.build_hash' => 'Mowfjkn',
    'container.build_id' => '2c0425cb',
    'container.build_time' => 1552125082,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMowfjkn');
