<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2pajyp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2pajyp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF2pajyp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF2pajyp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerF2pajyp\appDevDebugProjectContainer([
    'container.build_hash' => 'F2pajyp',
    'container.build_id' => 'aaeaa8fa',
    'container.build_time' => 1552318581,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2pajyp');
