<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPh4pkd8\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPh4pkd8/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPh4pkd8.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPh4pkd8\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPh4pkd8\appProdProjectContainer([
    'container.build_hash' => 'Ph4pkd8',
    'container.build_id' => '01bc6278',
    'container.build_time' => 1552054923,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPh4pkd8');
