<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPukkvbg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPukkvbg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPukkvbg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPukkvbg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPukkvbg\appProdProjectContainer([
    'container.build_hash' => 'Pukkvbg',
    'container.build_id' => '51314e35',
    'container.build_time' => 1552846235,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPukkvbg');
