<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxkb9au\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxkb9au/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYxkb9au.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYxkb9au\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYxkb9au\appProdProjectContainer([
    'container.build_hash' => 'Yxkb9au',
    'container.build_id' => '7837630f',
    'container.build_time' => 1552847318,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxkb9au');
