<?php

namespace ConnexionBundle\Repository;

/**
 * ContenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuRepository extends \Doctrine\ORM\EntityRepository
{
}
