<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHjfyfuo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHjfyfuo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHjfyfuo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHjfyfuo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHjfyfuo\appDevDebugProjectContainer([
    'container.build_hash' => 'Hjfyfuo',
    'container.build_id' => 'e6e92072',
    'container.build_time' => 1552990063,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHjfyfuo');
