<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxtb3to\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxtb3to/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYxtb3to.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYxtb3to\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYxtb3to\appDevDebugProjectContainer([
    'container.build_hash' => 'Yxtb3to',
    'container.build_id' => '3912ef4c',
    'container.build_time' => 1552649136,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxtb3to');
